import assert from "node:assert/strict";
import test from "node:test";

async function render(pathname = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${pathname}`, { headers: { accept: "text/html" } }), {
    ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) },
  }, { waitUntil() {}, passThroughOnException() {} });
}

test("server-renders the game portal", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<title>游点意思 · 移动游戏实验场<\/title>/i);
  assert.match(html, /<main class="portal-page">/i);
  assert.match(html, /小屏幕/);
  assert.match(html, /光脉：节拍反应/);
  assert.match(html, /见缝插针/);
  assert.match(html, /围住小猫/);
  assert.match(html, /记忆翻牌/);
  assert.match(html, /扫雷/);
  assert.match(html, /雷电射击/);
  assert.match(html, /水排序/);
  assert.match(html, /推箱子/);
  assert.match(html, /连线不交叉/);
  assert.match(html, /2048/);
  assert.match(html, /贪吃蛇/);
  assert.match(html, /打砖块/);
  assert.match(html, /合成果实/);
  assert.match(html, /霓虹深空/);
  assert.match(html, /律动光轨/);
  assert.match(html, /跳一跳/);
  assert.match(html, /方块倾落/);
  assert.match(html, /一笔画/);
  assert.match(html, /管道连接/);
  assert.match(html, /切水果/);
  assert.match(html, /宝石消消/);
  assert.match(html, /堆塔/);
  assert.match(html, /打地鼠/);
  assert.match(html, /数字华容道/);
  assert.match(html, /记忆序列/);
  assert.match(html, /青蛙过河/);
  assert.match(html, /云端跳跳/);
  assert.match(html, /恐龙快跑/);
  assert.match(html, /五子棋/);
  assert.match(html, /天降小鸡/);
  assert.match(html, /黑白棋/);
  assert.match(html, /点点消除/);
  assert.match(html, /迷宫寻宝/);
  assert.match(html, /射击靶场/);
  assert.match(html, /数独小解/);
  assert.match(html, /钟摆跳/);
  assert.match(html, /孔明棋/);
  assert.match(html, /着陆器/);
  assert.match(html, /弹幕躲避/);
  assert.match(html, /熄灯挑战/);
  assert.match(html, /迷你高尔夫/);
  assert.match(html, /24点挑战/);
  assert.match(html, /\/games\/pulse\//);
  assert.match(html, /\/games\/catch-the-cat\//);
  assert.match(html, /\/games\/merge-2048\//);
  assert.match(html, /\/games\/snake\//);
  assert.match(html, /\/games\/breakout\//);
  assert.match(html, /\/games\/fruit-merge\//);
  assert.match(html, /\/games\/neon-raid\//);
  assert.match(html, /\/games\/beat-line\//);
  assert.match(html, /\/games\/hold-jump\//);
  assert.match(html, /\/games\/block-fall\//);
  assert.match(html, /\/games\/one-stroke\//);
  assert.match(html, /\/games\/pipe-connect\//);
  assert.match(html, /\/games\/slice-fruit\//);
  assert.match(html, /\/games\/gem-match\//);
  assert.match(html, /\/games\/stack-tower\//);
  assert.match(html, /\/games\/whack-mole\//);
  assert.match(html, /\/games\/slide-puzzle\//);
  assert.match(html, /\/games\/memory-sequence\//);
  assert.match(html, /\/games\/frog-cross\//);
  assert.match(html, /\/games\/sky-hop\//);
  assert.match(html, /\/games\/dino-run\//);
  assert.match(html, /\/games\/gomoku\//);
  assert.match(html, /\/games\/basket-catch\//);
  assert.match(html, /\/games\/reversi\//);
  assert.match(html, /\/games\/same-pop\//);
  assert.match(html, /\/games\/maze-run\//);
  assert.match(html, /\/games\/aim-shot\//);
  assert.match(html, /\/games\/mini-sudoku\//);
  assert.match(html, /\/games\/pendulum-jump\//);
  assert.match(html, /\/games\/peg-solitaire\//);
  assert.match(html, /\/games\/lunar-lander\//);
  assert.match(html, /\/games\/bullet-dodge\//);
  assert.match(html, /泡泡龙/);
  assert.match(html, /气垫球/);
  assert.match(html, /\/games\/bubble-shooter\//);
  assert.match(html, /\/games\/air-hockey\//);
  assert.match(html, /\/games\/lights-out\//);
  assert.match(html, /\/games\/mini-golf\//);
  assert.match(html, /\/games\/twenty-four\//);
  assert.match(html, /\/play\/cloud-match/);
  assert.match(html, /game-icon-arcade/);
  assert.match(html, /游戏分类/);
  assert.match(html, /全部/);
  assert.match(html, /上滑加载更多|已经看到全部游戏/);
  assert.doesNotMatch(html, /GAME STUDIO|一个命令，|玩本周新作/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});

test("server-renders a sandboxed external game player", async () => {
  const response = await render("/play/cloud-match");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<title>云朵消消乐 · 游点意思<\/title>/i);
  assert.match(html, /src="https:\/\/xiaoxiaole\.lacknb\.com\/"/);
  assert.match(html, /sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock allow-popups"/);
  assert.match(html, /返回游戏列表/);
  assert.match(html, /新窗口/);
  assert.match(html, /重新加载云朵消消乐/);
  assert.match(html, /xiaoxiaole\.lacknb\.com(?:<!-- -->)? · 安全嵌入/);
});

test("server-renders the undercover game in the external player", async () => {
  const response = await render("/play/undercover");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<title>谁是卧底 · 游点意思<\/title>/i);
  assert.match(html, /src="https:\/\/undercover\.lacknb\.com\/"/);
  assert.match(html, /sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock allow-popups"/);
  assert.match(html, /重新加载谁是卧底/);
  assert.match(html, /卧<!-- --> · LOADING|卧 · LOADING/);
  assert.doesNotMatch(html, /CLOUD MATCH · LOADING/);
  assert.match(html, /undercover\.lacknb\.com(?:<!-- -->)? · 安全嵌入/);
});
