import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const gamesRoot = path.join(root, "games");
const iframeGamesRoot = path.join(root, "catalog/iframe");
const output = path.join(root, "packages/game-catalog/src/generated.ts");
const directories = await readdir(gamesRoot, { withFileTypes: true });
const games = [];
const gameIcons = new Set(["cat", "pin", "pulse", "cloud", "memory", "mine", "shooter", "water", "sokoban", "connect", "undercover", "arcade"]);

function addManifest(manifest, source) {
  if (!/^[a-z][a-z0-9-]*$/.test(manifest.id ?? "")) {
    throw new Error(`${source}: invalid game id`);
  }
  if (games.some((game) => game.id === manifest.id)) {
    throw new Error(`${source}: duplicate game id "${manifest.id}"`);
  }
  if (!gameIcons.has(manifest.icon)) {
    throw new Error(`${source}: invalid or missing game icon`);
  }
  if (manifest.launchMode === "iframe") {
    const embedUrl = new URL(manifest.embedUrl);
    if (embedUrl.protocol !== "https:") {
      throw new Error(`${source}: iframe games must use an HTTPS embedUrl`);
    }
    if (!manifest.path?.startsWith("/play/")) {
      throw new Error(`${source}: iframe game path must start with /play/`);
    }
  }
  if (manifest.enabled !== false) games.push(manifest);
}

for (const directory of directories.filter((item) => item.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
  const manifestPath = path.join(gamesRoot, directory.name, "public/game.json");
  try {
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    addManifest(manifest, manifestPath);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
}

try {
  const iframeManifests = await readdir(iframeGamesRoot, { withFileTypes: true });
  for (const file of iframeManifests.filter((item) => item.isFile() && item.name.endsWith(".json")).sort((a, b) => a.name.localeCompare(b.name))) {
    const manifestPath = path.join(iframeGamesRoot, file.name);
    addManifest(JSON.parse(await readFile(manifestPath, "utf8")), manifestPath);
  }
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}

const source = `import type { GameCatalogItem } from "./index";\n\n// Generated by \`npm run catalog:generate\`. Do not edit by hand.\nexport const games: GameCatalogItem[] = ${JSON.stringify(games, null, 2)};\n`;
await writeFile(output, source);
console.log(`Catalog generated with ${games.length} game(s).`);
