import type { GameCatalogItem } from "./index";

// Generated by `npm run catalog:generate`. Do not edit by hand.
export const games: GameCatalogItem[] = [
  {
    "id": "catch-the-cat",
    "title": "围住小猫",
    "shortTitle": "CAT",
    "description": "点击圆点设置路障，在小猫逃到边缘前围住它。",
    "category": "益智",
    "engine": "phaser",
    "orientation": "portrait",
    "version": "1.0.0",
    "path": "/games/catch-the-cat/",
    "enabled": true
  },
  {
    "id": "pin-gap",
    "title": "见缝插针",
    "shortTitle": "PIN",
    "description": "看准空隙，把所有针安全插进旋转圆盘。",
    "category": "休闲",
    "engine": "phaser",
    "orientation": "portrait",
    "version": "1.0.0",
    "path": "/games/pin-gap/",
    "enabled": true
  },
  {
    "id": "pulse",
    "title": "光脉：节拍反应",
    "shortTitle": "PULSE",
    "description": "在光环重合的一刻按下屏幕。",
    "category": "反应力",
    "engine": "phaser",
    "orientation": "portrait",
    "version": "1.0.0",
    "path": "/games/pulse/",
    "enabled": true
  },
  {
    "id": "cloud-match",
    "title": "云朵消消乐",
    "shortTitle": "云",
    "description": "轻点相邻云朵，享受一局轻松的消除游戏。",
    "category": "休闲",
    "engine": "iframe",
    "orientation": "portrait",
    "version": "external",
    "path": "/play/cloud-match",
    "launchMode": "iframe",
    "embedUrl": "https://xiaoxiaole.lacknb.com/",
    "enabled": true
  }
];
